### ISSUE TITLE
Create a OpenSource softwares database à la AlternativeTo.net 

### ISSUE THREAD

**Issue by dannycolin** [OpenScienceMOOC/Main#19]
As mentionned in #17 and other issues before that there's seems to be an interest in creating a Open Source software database à la AlternativeTo.net. This issue is to discuss a bit more about what we need to do and how we need to do it to make it hapen. :)

**Comment by Protohedgehog** [comment]
I think @jcolomb was interested in doing something like this too?

**Comment by nemobis** [comment]
The French (Framasoft people and the like) have settled on just using Wikipedia, starting from:
https://fr.wikipedia.org/wiki/Correspondance_entre_logiciels_libres_et_logiciels_propri%C3%A9taires

**Comment by dannycolin** [comment]
@nemobis I know both of this resource and I really appreciate the effort of everyone who contribute to them but we must admit:

1. The design is so awful both in term of esthetic and usability
2. Wiki's engines are a PITA to search software. Scrolling and clicking your way through a lot of pages is the kind of thing that keeps people on Windows and Mac.
3. There's no feedback from the community about the proposed alternative. I think that's something very important when you're not familiar with a new software. You want to know which apps in the list would probably be the best for your needs.

**Comment by alexmorley** [comment]
I agree with @dannycolin 's suggested improvements. And I'd really like to build a "proper" database on which we can have a open API (to enable search, discovery, rating, review and contributions - and people to build other apps using it). AFAICT that's not available with these?

However I hadn't seen either of these on my searches so thanks a lot @nemobis for posting them here :smile: .

There's also https://www.osalt.com/ but I think it hasn't been updated in some years (or at least it's security certificate hasn't :cry:

**Comment by alexmorley** [comment]
Also @nemobis do you know who the dedicated intern is? Can we tag him on here for discussion?

**Comment by johav** [comment]
Does anyone know where [JROST](https://jrost.org/) stands atm? I just signed up with Africarxiv.
In a course I gave this week on digital tools for Science Project management I started plotting some tools here: https://github.com/access2perspectives/Science_Project_Management/issues
and would like to be able to display this in a database sorted by 
- open  source versus commercial tools
- legal aspects: intellectual property, data security, privacy
- functionality: services covered by the tools, searchable as lists and multiple services tagged

Some of you might also know the page http://connectedresearchers.com/ - I am in talks with Thomas Cruzier how best to continue his efforts in a sustainable and potentially crowdsourced way.

**Comment by nemobis** [comment]
Alexander Morley, 16/11/18 12:57:
> Also @nemobis <https://github.com/nemobis> do you know who the dedicated 
> intern is? Can we tag him on here for discussion?

There's some information at 
<https://www.fsf.org/blogs/sysadmin/the-completion-of-davids-internship-work-on-the-free-software-directory> 
and previous blog posts. Looks like the internship is over.

**Comment by dannycolin** [comment]
@alexmorley having an API would definitely be awesome! Btw, did you contact the owner of osalt.com?

I've tried to contact the owner of openscience.org but didn't get any response back. :( Could be nice to retry and get in touch with him because the website hasn't been updated for a while.

**Comment by johav** [comment]
thanks a lot @bmkramer and apologies for the delayed reply. 
What a beautiful approach to getting hold of the high number of tools available! Thanks for pointing this out - I will happily implement more of your resources in upcoming courses.

Looks like a living database with all kinds of tools/functionalities/Licences/interoperability implemented will take some dedicated sessions and Mozilla sprints to bring to life... :/ would such be wortwhile the effort you think?
Any ways we can raise funds to do that collaboratively perhaps also with Thomas Cruzier's www.connectedresearchers.com platform content? And I have seen similar attempts elsewhere, which could be recruited.
So maybe starting by defining the criteria and sending out and disseminate a(nother) survey could be a start. Who'd be in?

**Comment by alexmorley** [comment]
I'm definitely in. And I have a little time and some resources  to make it happen. For me it's definitely worth the time as I have a scheme on how we can use it to help open projects get income.

I was thinking of creating another repo called MOD (meta open database - working title haha) where we can move forward with this?

**Comment by alexmorley** [comment]
Also thanks a lot @bmkramer. It was a super useful novel!

**Comment by johav** [comment]
Cool, let's do it! And yes, a dedicated repo looks like a good start - once we have criteria settled we can test all kinds of open databases to feed with the content. The working title sounds perfect! Go ahead, I'll join right away :) Who else?

**Comment by Protohedgehog** [comment]
@alexmorley @johav Feel free to create this repo within the OS MOOC project, if you want.

**Comment by dannycolin** [comment]
I'm definitely in ;)! Btw, here's the repo https://github.com/OpenScienceMOOC/opendatabase

**Comment by jcolomb** [comment]
We may link this to a discussion we had somewhere else: https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/issues/35

**Comment by alexmorley** [comment]
Hey! Sorry I was traveling yesterday. I was starting to work on this one below and ideally need to keep it slightly separate from the MOOC as it will make it easier to apply for money to make this sustainable. I'm happy to copy stuff between the two or whatever makes sense for other people! 

https://github.com/alexmorley/meta-open-database

**Comment by dannycolin** [comment]
@alexmorley oh sorry for the misunderstanding :) I'll close the one in OpenScienceMOOC then.

**Comment by alexmorley** [comment]
Not at all I was being slow! I have added @dannycolin and @johav as collabs. Anyone else who would like to cotlntribute LMK.

**Comment by dannycolin** [comment]
@heitorPB @nemobis @jcolomb quick reminder that further discussion on this project will happen [here](https://github.com/alexmorley/meta-open-database). 

Closing this issue now :).
