### ISSUE TITLE
Convert MOOC planning template.docx into markdown

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/Main#2]
Tried using Pandoc for this, and a couple of online services, but no luck! Anyone know of a service that works well for tabulated docx files?

**Comment by Protohedgehog** [comment]
Should have added a link to the actual file.. https://github.com/OpenScienceMOOC/Main/blob/master/Production_Files/MOOC%20planning%20template.docx

**Comment by Kevin-Mattheus-Moerman** [comment]
Does this help? (click edit on this comment to see raw markdown):

|  Design Phase  |  Delivered  |  Status badge  |  Deadline | Comments  |
|  ------------------  |  ------------  | -----------------  |  ------------ | -------------  |
| **Create table**  |                   |                         |                 |                    |
|  Make a table             |  Yep        |  :+1:   |  2018/05/10 | it is pretty |
|  Make a table             |  Yep        |  :heavy_check_mark:    |  2018/05/10 | it is pretty |
|  Make a table             |  Nope      |  :skull_and_crossbones:    |  2018/05/10 | dead end |
|  Make a table             |  Nope      |  :snail:     |  2018/05/10 | too slow |
|  Make a table             |  Yep        |  ![Green](https://img.shields.io/badge/Status-text-green.svg)   |  2018/05/10 | it is pretty |

Some cool icons to use for badges: 
:+1:
:-1: 
:raised_hand_with_fingers_splayed: 

Or:
:red_circle:  
:green_heart: 
:large_orange_diamond: 
  
Or status badges: 
![Red](https://img.shields.io/badge/Status-text-red.svg)
![Orange](https://img.shields.io/badge/Status-text-orange.svg)
![Green](https://img.shields.io/badge/Status-text-green.svg)

The table markdown looks slightly complicated of course. Its more common to use tickboxes like below to denote task completion, e.g.: 
```markdown
- [ ] Prepare module
```
Which creates:  
- [ ] Prepare module

You could do something like:
# To do list 

## Module 1
**Dead line**: 2018/05/10
**Comments**: Some text
![Green](https://img.shields.io/badge/Status-DONE-green.svg)
- [ ] Prepare module
- [ ] Prepare module

## Module 2
**Dead line**: 2018/05/10
**Comments**: Some text
![Green](https://img.shields.io/badge/Status-NEEDS_WORK-red.svg)
- [ ] Prepare module
- [ ] Prepare module

This [cheatsheet :notebook_with_decorative_cover: ](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) is super helpful

**Comment by jdpigeon** [comment]
Join the Mark Side
