### ISSUE TITLE
URL error in MOOC_presentation

### ISSUE THREAD

**Issue by TimSmithCH** [OpenScienceMOOC/Main#21]
The sticker slide (no.26) contains a Zenodo URL which goes nowhere. The correct URL should be: https://zenodo.org/record/1285575 
Also I note that that Zenodo record uses CC-by-4.0 when you actually want CC0 - in fact CC0 is available in Zenodo, and it is possible to update the record and republish it with this more general waiver if you wish
Best Regards, Tim

**Comment by Protohedgehog** [comment]
Awesome, thanks @TimSmithCH - have edited this and updated the presentation now. https://github.com/OpenScienceMOOC/Main

Re. licensing, not my choice on this one. Melanie is the one who designed it, and up to her :)
