### ISSUE TITLE
Defective Slack invite link

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/Main#26]
Not sure what happened here. This link: https://openmooc-ers-slackin.herokuapp.com/ usually enabled people to join the Slack group automatically without invite, but now returns an application error.

I think this is the tool we were using before: https://github.com/rauchg/slackin

Any assistance on fixing/rebuilding this would be appreciated. Can provide Slack admin upgrade if needed.

**Comment by SamGuay** [comment]
Just quick note, the link on the website points to the broken link.

**Comment by Protohedgehog** [comment]
@SamGuay oops which part of the website, sorry? Will fix right away :)

**Comment by Protohedgehog** [comment]
Should be fixed now, thanks!
