### ISSUE TITLE
get (non-male) confidants for code of conduct

### ISSUE THREAD

**Issue by jcolomb** [OpenScienceMOOC/Main#3]
Who would volunteer?

Could we also use have the mozilla confidant during the sprint?

**Comment by bmkramer** [comment]
Happy to do that - will also be a good learning experience.

**Comment by jcolomb** [comment]
Do we have any both non-male and non-female person in our community that would volunteer ?

Jon, you will update the COC file, right?

**Comment by Protohedgehog** [comment]
Cool, thanks for updating Julien. Will have to remember to update when the new site is running too.
