### ISSUE TITLE
How to become a member of this organization?

### ISSUE THREAD

**Issue by ucalyptus** [OpenScienceMOOC/Main#34]
Profile - @ucalyptus

**Comment by ivogrigorov** [comment]
Hey Sayantan!

You have :)
Welcome!

Create a SLACK account and I’ll introduce you to the community. Tell us two sentences what competencies you could contribute to Open Science MOOC development.

Now that we have your GitHub user, we’ll add you on the git site where most of the development happens.

Thank you for your enthusiasm for Open Science.

On behalf of Steering Committee

Ivo Grigorov



Research Secretariat



DTU Aqua



Danmarks Tekniske Universitet/
Technical University of Denmark
Institut for Akvatiske Ressourcer

Kemitorvet, Bldng 201, rm 237
Kongens Lyngby, 2800, Denmark


Direct +45 21 31 63 74<tel:+45%2021%2031%2063%2074>
ivgr@aqua.dtu.dk<mailto:ivgr@aqua.dtu.dk>
www.aqua.dtu.dk<http://www.aqua.dtu.dk/>

Twitter<https://twitter.com/OAforClimate> | LinkedIn Profile <https://www.linkedin.com/in/ivogrigorov/> | Skype Contact: ivo_grigorov


[Beskrivelse: http://www.dtu.dk/images/DTU_email_logo_01.gif]





On 20 Nov 2019, at 14.56, Sayantan Das <notifications@github.com<mailto:notifications@github.com>> wrote:


Profile - @ucalyptus<https://github.com/ucalyptus>

**Comment by ucalyptus** [comment]
I have a slack account . Can you send me the slack invite form at sayantandas30011998@gmail.com
