### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by thehassantahir** [OpenScienceMOOC/Main#39]
**Describe the bug**
Submitting username to join organization ends up in internal server error

**To Reproduce**
1. Go to '[site](https://open-science-mooc-invite.herokuapp.com/)'
2. Type your 'Username' 
3. See error

**Expected behavior**
Should go on the thank you page or other landing page

**Screenshots**
![Screenshot from 2021-11-20 18-22-04](https://user-images.githubusercontent.com/54933420/142727930-7876f8e9-6f13-4b3f-9f45-a40114fb47a0.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Chrome]
 - Version [e.g. 95.0]

**Additional context**
If you are accepting new invites for you organization please consider me as a full stack python developer @thehassantahir

**Comment by jcolomb** [comment]
the heroic app is indeed broken #37 #38, I will invite you by hand
